# Generated by Django 5.0 on 2024-01-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_comcomment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comcomment",
            name="comId",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="post",
            name="post_id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
