# Generated by Django 5.0 on 2024-02-01 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_alter_comments_comment_id_alter_like_like_id_profile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="friend",
            old_name="friend_id",
            new_name="friend",
        ),
        migrations.RenameField(
            model_name="friend",
            old_name="user_id",
            new_name="user",
        ),
    ]
