# Generated by Django 5.0 on 2024-02-01 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_rename_friend_id_friend_friend_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friend",
            name="friend",
            field=models.ManyToManyField(to="home.friend"),
        ),
    ]
