# Generated by Django 5.0 on 2024-02-01 05:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_alter_friend_friend"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="friend",
            name="friend",
            field=models.ManyToManyField(
                related_name="friends", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
